config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  devise_for :users
  get 'home/about' => 'homes#about', as: 'about'
  resources :users, only: [:index, :create, :show, :edit, :update] do
    resources :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
  	  get "followers" => "relationships#followers", as: "followers"
  end
  resources :books, only: [:index, :show, :create, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, pnly: [:create, :destroy]
  end
  get '/search' => 'searches#search'
  resources :notifications, only: [:update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
 def create
   @book = Book.find(params[:book_id])
   @comment = current_user.book_comments.new(book_comment_params)
   @comment.book_id = @book.id
   @comment.save
  # redirect_to request.referer
 end

  def destroy
    @book = Book.find(params[:book_id])
    @comment = BookComment.find(params[:id])
    @comment.destroy
    # redirect_to request.referer
  end
  
  private
  
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
  
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_form.html.erb
<%= form_with model: [book, book_comment], local: false do |f| %>
  <div class="form-group">
    <%= f.text_area :comment, rows: "5", class: "form-control", id: "text" %>
  </div>
  <div class="form-group">
    <%= f.submit "送信", class: "btn btn-sm btn-secondary" %>
  </div>
<% end %>

app/views/book_comments/_index.html.erb
<table>
  <tbody>
    <% book.book_comments.each do |book_comment| %>
      <tr>
        <td>
          <%= link_to user_path(book_comment.user) do %>
            <%= image_tag book_comment.user.get_profile_image, size: "50x50"%><br>
            <%= book_comment.user.name %>
          <% end %>
        </td>
        <td><%= book_comment.comment %></td>
        <% if book_comment.user == current_user %>
          <td><%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-sm btn-danger", remote: true %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/book_comments/create.js.erb
$("#comment_index").html("<%= j(render "book_comments/index", book: @book) %>")
$("#comment_count").html("コメント数：<%= @book.book_comments.count %>")
$("#text").val("")

app/views/book_comments/destroy.js.erb
$("#comment_index").html("<%= j(render 'book_comments/index', book: @book) %>")
$("#comment_count").html("コメント数：<%= @book.book_comments.count %>")