config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  devise_for :users
  get 'home/about' => 'homes#about', as: 'about'
  resources :users, only: [:index, :create, :show, :edit, :update] do
    resources :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
  	  get "followers" => "relationships#followers", as: "followers"
  end
  resources :books, only: [:index, :show, :create, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, pnly: [:create, :destroy]
  end
  get '/search' => 'searches#search'
  resources :notifications, only: [:update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  # アソシエーションと一覧表示のためにフォロー中の人を取得（ソースは相手がフォローされている人から持ってきて自分のフォローしている人として表示）
  has_many :relationships, foreign_key: :following_id , dependent: :destroy
  has_many :followings, through: :relationships, source: :follower
  # アソシエーションと一覧表示のためにフォロワー取得（ソースは相手が自分をフォローしている人から持ってきて自分がフォローされている人として表示）
  has_many :reverse_relationships, class_name: "Relationship", foreign_key: :follower_id, dependent: :destroy
  has_many :followers, through: :reverse_relationships, source: :following
  has_many :notifications, dependent: :destroy

  has_one_attached :profile_image

  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: {maximum: 50 }

  def get_profile_image
    (profile_image.attached?)? profile_image : 'no_image.jpg'
  end

  def already_favorited?(book)
    self.favorites.exists?(book_id: book.id)
  end

  def followed_by?(user)
     followings.include?(user)
  end

  def self.search_for(pattern,word)
    if pattern == 'perfect'
      User.where(name: word)
    elsif pattern == 'forward'
      User.where('name LIKE ?', word + '%')
    elsif pattern == 'backward'
      User.where('name LIKE ?', '%' + word )
    else
      User.where('name LIKE ?', '%' + word + '%')
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:update, :edit]
  
  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def create
     @user.save
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      flash[:alert] = "You have not successfully updated."
      render :edit
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to books_path
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th scopre="col">image</th>
      <th scopre="col">name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: "80x80" %></td>
        <td><%= user.name %></td>
        <td>フォロー数：<%= user.followings.count%></td>
        <td>フォロワー数：<%= user.followers.count%></td>
        <% if current_user != user %>
          <td><%= render 'relationships/btn', user: user, options: { class: "link" } %></td>
        <% end %>
        <td><%= link_to "Show",user_path(user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class="table">
  <tr><%= image_tag user.get_profile_image, size: "100x100" %></tr>
  <tr>
    <th>name</th>
    <th><%= user.name %></th>
  </tr>
  <tr>
    <th>introduction</th>
    <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to user.followings.count, user_followings_path(user) %></th>
  </tr>
    <tr>
    <th>followers</th>
    <th><%= link_to user.followers.count, user_followers_path(user) %></th>
  </tr>
</table>
<div class="row">
  <% if current_user != user %>
    <%= render 'relationships/btn', user: user, options: { class: "" } %>
  <% else %>
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
      <i class="fa-solid fa-user-gear"></i>
    <% end %>
  <% end %>

</div>

app/views/users/edit.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <%= render 'layouts/errors', obj: @user %>
      <%= form_with model: @user do |f| %>
        <div class="form_group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control name" %>
        </div>
        <div class="form_group">
          <%= f.label :image %>
          <%= f.file_field :profile_image, class: "form-control-file image", accept: "image/*" %>
        </div>
        <div class="form_group">
          <%= f.label :introduction %>
          <%= f.text_area :introduction, class: "form-control introduction" %>
        </div>
        <div class= "form_group">
          <%= f.submit "Update User", class: "btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <%= render 'layouts/errors', obj: @user %>
  <div class="row">
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info',user: current_user %><!--部分テンプレート貼る-->
      <h2>New Book</h2>
      <%= render 'books/form', book: @book%>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <%= render 'index', users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %><!--部分テンプレート貼る-->
      <h2>New Book</h2>
      <%= render 'books/form', book: @book%>
    </div>    
     <!--ユーザーbook詳細-->
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th scopre="col">Title</th>
            <th scopre="col">Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                  <%= image_tag book.user.get_profile_image, size: "80x80" %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(book) do %>
                  <%= book.title %>
                <% end %>
              </td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <!--ここまで-->
  </div>
</div>